# Aqui irei definir o nome do pipeline

name: Meu primeiro workflow

# Quais eventos (gatilhos) desparam o fluxo?
# Temos eventos do tipo push, pull request, merge, etc.

on:
  push: 
      branches: [main, master, develop]
      
  pull_request:
      branches: 
      - main
      - master
      - develop
  
# Quais são os trabalhos (tarefas)  a serem executados pelo o workflow

jobs:

  tarefa1: 
      name: Primeira tarefa
      runs-on: ubuntu-latest
      
      steps: 
        - name: Passo1
          needs: tarefa3
          run: echo "Executando o passo 1"
        - name: Passo2
          run: echo "Executando o passo 2"
        - name: Passo 3
          run: echo "Executando o passo 3"

  tarefa2: 
      name: Segunda tarefa
      runs-on: ubuntu-latest
      
      steps: 
        - name: Passo4
          needs: tarefa1 
          run: echo "Executando o passo 4"
        - name: Passo5
          run: echo "Executando o passo 5"
        - name: Passo6
          run: echo "Executando o passo 6"

  tarefa3: 
      name: Terceira tarefa
      runs-on: ubuntu-latest
      
      steps: 
        - name: Passo7
          needs: tarefa2 
          run: echo "Executando o passo 7"
        - name: Passo8
          run: echo "Executando o passo 8"
        - name: Passo9
          run: echo "Executando o passo 9"
